name: PR Check

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Label PR
      uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  size-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check changed files
      run: |
        git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} > changed_files.txt
        echo "Changed files:"
        cat changed_files.txt

    - name: Warn on large changes
      run: |
        file_count=$(wc -l < changed_files.txt)
        if [ $file_count -gt 50 ]; then
          echo "::warning::This PR modifies $file_count files. Consider breaking it into smaller PRs."
        fi
